<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ARM.Mesa.Bursatil.Models\ARM.Mesa.Bursatil.Models.csproj" />
    <ProjectReference Include="..\ARM.Mesa.Bursatil.Services\ARM.Mesa.Bursatil.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\js\" />
  </ItemGroup>


  <ItemGroup>
    <Content Update="wwwroot\mesa-bursatil-preview.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
