<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ARM.Mesa.Bursatil.Services/ARM.Mesa.Bursatil.Services.csproj" />
    <ProjectReference Include="../ARM.Mesa.Bursatil.Sync/ARM.Mesa.Bursatil.Sync.csproj" />
  </ItemGroup>
</Project>
